### PR TITLE
Fix typo on `validate` error message when not passing an instance

### PR DESCRIPTION
**Pull request by alombarte**

### CODE REVIEW

**Review by jviotti — APPROVED** [review]
Thanks!

**Comment by jviotti** [comment]
@alombarte You will need to adjust one of the tests too, which asserts on the expected output:

```diff
diff --git a/test/validate/fail_no_instance.sh b/test/validate/fail_no_instance.sh
index 487b8d3..af6d5f6 100755
--- a/test/validate/fail_no_instance.sh
+++ b/test/validate/fail_no_instance.sh
@@ -18,7 +18,7 @@ EOF
 test "$CODE" = "1" || exit 1

 cat << 'EOF' > "$TMP/expected.txt"
-error: In addition to the schema, you must also pass a argument
+error: In addition to the schema, you must also pass an argument
 that represents the instance to validate against. For example:

   jsonschema validate path/to/schema.json path/to/instance.json
```

**Comment by alombarte** [comment]
Test fixed. I haven't touched C++ source code since year 99 or so :sweat:

**Comment by jviotti** [comment]
Haha C++ evolved a lot. Definitely a VERY cool language nowadays.

**Pull request merged**
